excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://jediscripts.github.io
title: JediScript
tagline: May the Force be with you
description: Um hackerspace para jovens Padawans! </br>Que a Força esteja com você, e lembre-se de passar o que você aprendeu.
paginate: 3
