excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://jediscripts.github.io
title: JediScript
tagline: May the Force be with you
description: Um hackerspace para jovens Padawans!
paginate: 3
